# Generated by Django 3.1.1 on 2020-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hobby_server',
            field=models.BooleanField(default=False, help_text='Is project currently running on hobby tier server?'),
        ),
        migrations.AlterField(
            model_name='language',
            name='category',
            field=models.CharField(choices=[('FRO', 'Frontend'), ('BAC', 'Backend'), ('FRA', 'Framework/Library'), ('MAR', 'Markup'), ('OTH', 'Other')], help_text='Choose the primary category for the language', max_length=3),
        ),
        migrations.AlterField(
            model_name='projectlanguage',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Select the languages involved in the project', related_name='languages_used', to='api.Language'),
        ),
    ]
