# Generated by Django 3.1.1 on 2020-09-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200919_1118'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectlanguage',
            name='A value between 1 and 100 is required',
        ),
        migrations.RemoveField(
            model_name='projectlanguage',
            name='language',
        ),
        migrations.AddField(
            model_name='projectlanguage',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Select the language(s) involved in the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages_used', to='api.language'),
        ),
        migrations.AlterField(
            model_name='projectlanguage',
            name='percent_used',
            field=models.IntegerField(default=1, help_text='Enter a number between 1 and 100 to signify language usage.'),
        ),
        migrations.AddConstraint(
            model_name='projectlanguage',
            constraint=models.CheckConstraint(check=models.Q(('percent_used__gte', 1), ('percent_used__lte', 100)), name='A value between 1 and 100 is required.'),
        ),
    ]
