# Generated by Django 3.0.8 on 2020-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200925_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter icon class name for this category (optional).', max_length=30, null=True),
        ),
    ]
