# Generated by Django 3.1.1 on 2020-09-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200925_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlanguage',
            name='percent_used',
            field=models.IntegerField(blank=True, help_text='Enter a number between 1 and 100 to signify subject usage (optional).', null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the subject area (e.g. Python, Bootstrap or course)', max_length=50, unique=True)),
                ('logo_icon', models.CharField(blank=True, help_text='Enter icon class name (optional).', max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Which category does this subject belong to? (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_subjects', to='api.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='projectlanguage',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Select the language(s) involved in the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages_used', to='api.subject'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
