# Generated by Django 3.1.1 on 2020-10-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200928_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmedia',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.projectmedia'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='project_placeholder',
            field=models.FileField(blank=True, upload_to='project_placeholders'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Which category or categories is this subject related to? (optional)', related_name='cat_subjects', to='api.Category'),
        ),
    ]
