# Generated by Django 3.1.1 on 2020-10-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201006_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.project'),
        ),
    ]
