# Generated by Django 3.1.1 on 2020-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201006_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Lower numbers appear more prominently.', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='summary',
            field=models.TextField(help_text='Enter a brief intro to the section.', max_length=1000),
        ),
    ]
